export { createSupabaseClient } from "./client";
export {
  getCities,
  getCitiesWithShopCounts,
  getCityGuide,
  getProfile,
  isUsernameAvailable,
  saveIdentity,
  saveTastePicks,
  getRatedShopsInBounds,
  logShopVisit,
  getProfilesByIds,
  getCitiesByIds,
  getLogLikes,
  setLogLike,
  getComments,
  getCommentLikes,
  setCommentLike,
  postComment,
  getCommentCountsByLog,
  getFollowedUserIds,
  getFollowingFeedLogs,
  getFollowingFeedLists,
  getShopsInBounds,
  getLogsForShops,
  getLiveCityGuides,
  getShopDetail,
  getShopReviews,
  logVisit,
  getPublicProfileByUsername,
  getProfileStats,
  getProfileEntries,
  isFollowing,
  setFollow,
  updateProfile,
  getProfileVisitDates,
  getProfileFaves,
  getSavedShops,
  isShopSaved,
  setShopSaved,
  getFollowList,
  searchProfiles,
} from "./queries";
export type {
  ShopDetail,
  ShopReview,
  LogVisitInput,
  PublicProfile,
  ProfileStats,
  ProfileEntry,
  SavedShop,
  PersonRow,
} from "./queries";
export type { Database } from "./types";
